require('dotenv').config({ path: __dirname + '/../.env' });
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
const Blog = require('../src/modules/blog/blog.model');

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => {
    console.error('Failed to connect to MongoDB', err);
    process.exit(1);
  });

const importBlogs = async () => {
  try {
    const filePath = path.join(__dirname, 'blogs.json');
    
    if (!fs.existsSync(filePath)) {
      console.error('❌ Error: blogs.json not found in the scripts directory.');
      console.log('Please save the JSON generated by ChatGPT/Claude into backend/scripts/blogs.json and run this script again.');
      process.exit(1);
    }

    const fileContent = fs.readFileSync(filePath, 'utf-8');
    const blogsData = JSON.parse(fileContent);

    if (!Array.isArray(blogsData)) {
      throw new Error('JSON file should contain an array of blogs');
    }

    console.log(`Found ${blogsData.length} blogs in the JSON file. Preparing to import...`);

    // Add isPublished flag and format them
    const blogsToInsert = blogsData.map(blog => ({
      ...blog,
      isPublished: true, // Auto-publish them
    }));

    // Import into DB
    let successCount = 0;
    let errorCount = 0;

    for (const blog of blogsToInsert) {
      try {
        await Blog.updateOne(
          { slug: blog.slug }, // Match by slug
          { $set: blog }, // Update or Insert
          { upsert: true } // Create if doesn't exist
        );
        successCount++;
        console.log(`✅ Imported: ${blog.title}`);
      } catch (err) {
        errorCount++;
        console.error(`❌ Failed to import: ${blog.title} - ${err.message}`);
      }
    }

    console.log('\n--- Import Complete ---');
    console.log(`Successfully imported: ${successCount}`);
    console.log(`Failed: ${errorCount}`);
    
    process.exit(0);
  } catch (error) {
    console.error('Failed to run import script:', error);
    process.exit(1);
  }
};

importBlogs();
