// Mirrors backend shared/constants.js — keep in sync

export const PLANS = {
  FREE: 'free',
  PRO: 'pro',
};

export const ROLES = {
  STUDENT: 'student',
  EMPLOYER: 'employer',
  ADMIN: 'admin',
  SUPERADMIN: 'superadmin',
};

export const TOPICS = [
  { value: 'quantitative', label: 'Quantitative Aptitude' },
  { value: 'logical',      label: 'Logical Reasoning' },
  { value: 'verbal',       label: 'Verbal Ability' },
  { value: 'di',           label: 'Data Interpretation' },
  { value: 'dsa',          label: 'Data Structures & Algorithms' },
  { value: 'os',           label: 'Operating Systems' },
  { value: 'dbms',         label: 'DBMS' },
  { value: 'system-design',label: 'System Design' },
  { value: 'cn',           label: 'Computer Networks' },
  { value: 'oops',         label: 'OOP Concepts' },
  { value: 'sql',          label: 'SQL' },
  { value: 'se',           label: 'Software Engineering' },
  { value: 'web',          label: 'Web Technologies' },
  { value: 'cloud',        label: 'Cloud Computing' },
  { value: 'ml',           label: 'Machine Learning' },
];

// ─── Subtopics per parent topic ────────────────────────────────────────────
export const SUBTOPICS = {
  quantitative: [
    'number_system', 'hcf_lcm', 'percentages', 'profit_loss',
    'simple_compound_interest', 'compound_interest', 'ratio_proportion',
    'averages', 'mixtures_alligations', 'time_work', 'time_speed_distance',
    'permutation_combination', 'probability', 'boats_streams',
    'pipes_cistern', 'problems_on_trains', 'partnership', 'area',
    'volume_surface_area', 'surds_indices', 'simplification',
    'square_cube_root', 'problems_on_ages', 'banker_discount',
    'true_discount', 'odd_man_out', 'height_distance', 'stocks_shares',
  ],
  logical: [
    'coding_decoding', 'blood_relations', 'direction_sense', 'syllogisms',
    'seating_arrangement', 'number_series', 'letter_series', 'clocks',
    'calendars', 'venn_diagrams', 'statement_assumption', 'course_of_action',
    'statement_conclusion', 'cause_effect', 'logical_problems',
    'statement_argument', 'cube_dice', 'mirror_water_images',
    'embedded_figures', 'figure_matrix', 'grouping_of_figures',
    'paper_folding', 'verbal_reasoning', 'puzzles', 'data_sufficiency',
    'input_output', 'ranking_arrangement', 'alphanumeric_series',
    'analogy', 'classification',
  ],
  verbal: [
    'reading_comprehension', 'sentence_correction', 'synonyms', 'antonyms',
    'idioms_phrases', 'fill_in_blanks', 'para_jumbles',
    'one_word_substitution', 'spellings', 'sentence_improvement',
    'change_of_voice', 'selecting_words', 'active_passive_voice',
    'direct_indirect_speech', 'articles', 'prepositions', 'conjunctions',
    'closet_test', 'ordering_words',
  ],
  di: ['tabular', 'bar_graphs', 'line_charts', 'pie_charts'],
  dsa: [
    'arrays', 'strings', 'linked_list', 'trees', 'graphs', 'sorting',
    'searching', 'dynamic_programming', 'recursion', 'stack_queue', 'heap',
    'bit_manipulation', 'two_pointers', 'sliding_window', 'backtracking',
    'greedy', 'hashing', 'tries', 'segment_tree', 'matrix',
  ],
  os: ['processes', 'threads', 'scheduling', 'memory_management',
       'deadlocks', 'paging', 'file_systems'],
  dbms: ['normalization', 'sql_queries', 'transactions', 'indexing',
         'er_diagrams', 'concurrency'],
  sql: ['joins', 'subqueries', 'views', 'indexes', 'triggers',
        'aggregate_functions', 'window_functions'],
  cn: ['osi_model', 'tcp_ip', 'http_https', 'dns', 'routing', 'subnetting'],
  oops: ['inheritance', 'polymorphism', 'encapsulation', 'abstraction',
         'design_patterns'],
  'system-design': ['scalability', 'load_balancing', 'caching', 'databases',
                    'microservices', 'cap_theorem'],
  se:    ['sdlc', 'agile', 'testing', 'software_models', 'project_management'],
  web:   ['html_css', 'javascript', 'react', 'nodejs', 'dom', 'rest_api'],
  cloud: ['aws', 'azure', 'virtualization', 'saas_paas_iaas', 'cloud_security'],
  ml:    ['supervised_learning', 'unsupervised_learning', 'neural_networks',
          'deep_learning', 'statistics'],
};

// ─── Human-readable labels for every subtopic key ──────────────────────────
export const SUBTOPIC_LABELS = {
  // Quantitative
  number_system:             'Number System',
  hcf_lcm:                  'HCF & LCM',
  percentages:               'Percentages',
  profit_loss:               'Profit & Loss',
  simple_compound_interest:  'Simple Interest',
  compound_interest:         'Compound Interest',
  ratio_proportion:          'Ratio & Proportion',
  averages:                  'Averages',
  mixtures_alligations:      'Mixtures & Alligations',
  time_work:                 'Time & Work',
  time_speed_distance:       'Time, Speed & Distance',
  permutation_combination:   'Permutation & Combination',
  probability:               'Probability',
  boats_streams:             'Boats & Streams',
  pipes_cistern:             'Pipes & Cistern',
  problems_on_trains:        'Problems on Trains',
  partnership:               'Partnership',
  area:                      'Area',
  volume_surface_area:       'Volume & Surface Area',
  surds_indices:             'Surds & Indices',
  simplification:            'Simplification',
  square_cube_root:          'Square Root & Cube Root',
  problems_on_ages:          'Problems on Ages',
  banker_discount:           "Banker's Discount",
  true_discount:             'True Discount',
  odd_man_out:               'Odd Man Out & Series',
  height_distance:           'Height & Distance',
  stocks_shares:             'Stocks & Shares',
  // Logical
  coding_decoding:           'Coding & Decoding',
  blood_relations:           'Blood Relations',
  direction_sense:           'Direction Sense',
  syllogisms:                'Syllogisms',
  seating_arrangement:       'Seating Arrangement',
  number_series:             'Number Series',
  letter_series:             'Letter Series',
  clocks:                    'Clocks',
  calendars:                 'Calendars',
  venn_diagrams:             'Venn Diagrams',
  statement_assumption:      'Statement & Assumption',
  course_of_action:          'Course of Action',
  statement_conclusion:      'Statement & Conclusion',
  cause_effect:              'Cause & Effect',
  logical_problems:          'Logical Problems',
  statement_argument:        'Statement & Argument',
  cube_dice:                 'Cube & Dice',
  mirror_water_images:       'Mirror & Water Images',
  embedded_figures:          'Embedded Figures',
  figure_matrix:             'Figure Matrix',
  grouping_of_figures:       'Grouping of Figures',
  paper_folding:             'Paper Folding',
  verbal_reasoning:          'Verbal Reasoning',
  puzzles:                   'Puzzles',
  data_sufficiency:          'Data Sufficiency',
  input_output:              'Input & Output',
  ranking_arrangement:       'Ranking & Arrangement',
  alphanumeric_series:       'Alphanumeric Series',
  analogy:                   'Analogy',
  classification:            'Classification',
  // Verbal
  reading_comprehension:     'Reading Comprehension',
  sentence_correction:       'Sentence Correction',
  synonyms:                  'Synonyms',
  antonyms:                  'Antonyms',
  idioms_phrases:            'Idioms & Phrases',
  fill_in_blanks:            'Fill in the Blanks',
  para_jumbles:              'Para Jumbles',
  one_word_substitution:     'One Word Substitution',
  spellings:                 'Spellings',
  sentence_improvement:      'Sentence Improvement',
  change_of_voice:           'Change of Voice',
  selecting_words:           'Selecting Words',
  active_passive_voice:      'Active & Passive Voice',
  direct_indirect_speech:    'Direct & Indirect Speech',
  articles:                  'Articles',
  prepositions:              'Prepositions',
  conjunctions:              'Conjunctions',
  closet_test:               'Cloze Test',
  ordering_words:            'Ordering of Words',
  // DI
  tabular:                   'Table Charts',
  bar_graphs:                'Bar Graphs',
  line_charts:               'Line Charts',
  pie_charts:                'Pie Charts',
  // DSA
  arrays:                    'Arrays',
  strings:                   'Strings',
  linked_list:               'Linked List',
  trees:                     'Trees',
  graphs:                    'Graphs',
  sorting:                   'Sorting Algorithms',
  searching:                 'Searching Algorithms',
  dynamic_programming:       'Dynamic Programming',
  recursion:                 'Recursion',
  stack_queue:               'Stack & Queue',
  heap:                      'Heap',
  bit_manipulation:          'Bit Manipulation',
  two_pointers:              'Two Pointers',
  sliding_window:            'Sliding Window',
  backtracking:              'Backtracking',
  greedy:                    'Greedy Algorithms',
  hashing:                   'Hashing',
  tries:                     'Tries',
  segment_tree:              'Segment Tree',
  matrix:                    'Matrix / 2D Arrays',
  // OS
  processes:                 'Processes',
  threads:                   'Threads',
  scheduling:                'CPU Scheduling',
  memory_management:         'Memory Management',
  deadlocks:                 'Deadlocks',
  paging:                    'Paging & Segmentation',
  file_systems:              'File Systems',
  // DBMS
  normalization:             'Normalization',
  sql_queries:               'SQL Queries',
  transactions:              'Transactions & ACID',
  indexing:                  'Indexing',
  er_diagrams:               'ER Diagrams',
  concurrency:               'Concurrency Control',
  // SQL
  joins:                     'Joins',
  subqueries:                'Subqueries',
  views:                     'Views',
  indexes:                   'Indexes',
  triggers:                  'Triggers',
  aggregate_functions:       'Aggregate Functions',
  window_functions:          'Window Functions',
  // CN
  osi_model:                 'OSI Model',
  tcp_ip:                    'TCP/IP',
  http_https:                'HTTP & HTTPS',
  dns:                       'DNS',
  routing:                   'Routing',
  subnetting:                'Subnetting',
  // OOP
  inheritance:               'Inheritance',
  polymorphism:              'Polymorphism',
  encapsulation:             'Encapsulation',
  abstraction:               'Abstraction',
  design_patterns:           'Design Patterns',
  // System Design
  scalability:               'Scalability',
  load_balancing:            'Load Balancing',
  caching:                   'Caching',
  databases:                 'Databases',
  microservices:             'Microservices',
  cap_theorem:               'CAP Theorem',
  // SE
  sdlc:                      'SDLC',
  agile:                     'Agile & Scrum',
  testing:                   'Software Testing',
  software_models:           'Software Models',
  project_management:        'Project Management',
  // Web
  html_css:                  'HTML & CSS',
  javascript:                'JavaScript',
  react:                     'React',
  nodejs:                    'Node.js',
  dom:                       'DOM Manipulation',
  rest_api:                  'REST APIs',
  // Cloud
  aws:                       'AWS',
  azure:                     'Azure',
  virtualization:            'Virtualization',
  saas_paas_iaas:            'SaaS / PaaS / IaaS',
  cloud_security:            'Cloud Security',
  // ML
  supervised_learning:       'Supervised Learning',
  unsupervised_learning:     'Unsupervised Learning',
  neural_networks:           'Neural Networks',
  deep_learning:             'Deep Learning',
  statistics:                'Statistics & Probability',
};

export const DIFFICULTY_LEVELS = [
  { value: 'easy',   label: 'Easy',   color: 'text-green-500' },
  { value: 'medium', label: 'Medium', color: 'text-yellow-500' },
  { value: 'hard',   label: 'Hard',   color: 'text-red-500' },
];

export const COMPANIES = [
  'TCS', 'Infosys', 'Wipro', 'Accenture', 'Cognizant',
  'HCL', 'Capgemini', 'Tech Mahindra', 'Amazon', 'Zoho',
];

export const SESSION_TYPES = {
  PRACTICE:      'practice',
  DAILY:         'daily-challenge',
  MOCK:          'mock-test',
  COMPANY_MOCK:  'company-mock',
};

export const FREE_DAILY_QUESTION_LIMIT = 20;
